<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * FooterBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FooterBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
