<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * StoreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByKey($key)
	{
		
		if($key != '')
		{
			$i = 0;
			$search_string = '(';
			$keys = explode(' ', $key);
			foreach ($keys as $_key) {
				$search_string .= '(s.name LIKE \'%'.$_key.'%\'
						OR s.city LIKE \'%'.$_key.'%\'
						OR s.address LIKE \'%'.$_key.'%\')';

				if($i+1 < count($keys))
					$search_string .= ' AND ';
				$i++;
			}
			$search_string .= ')';

			$stores = $this->createQueryBuilder('s')
				->where($search_string)
				->getQuery()
				->getResult();
			return $stores;
		}
	}
}
