<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCountriesByCategory($id_category, $id_sub_category)
    {
        $qb = $this->createQueryBuilder('c')
            ->join('BDMNicolasBackendBundle:Product', 'p', 'WITH', 'c.id = p.country')
            ->join('BDMNicolasBackendBundle:ProductSubCategory', 's', 'WITH', 'p.sub_category = s.id');
        if ($id_sub_category != 0) {
            $qb->where('s.id = :id_sub_category')
                ->setParameter('id_sub_category', $id_sub_category);
        } else {
            $qb->join('BDMNicolasBackendBundle:ProductCategory', 'cat', 'WITH', 'cat.id = s.category')
                ->where('cat.id = :id')
                ->setParameter('id', $id_category);
        }
        return $qb->getQuery()
            ->getResult();
    }
}
