<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * ProductSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSubCatsByCategory($id_category)
    {
        return $this->createQueryBuilder('s')
            ->where('s.category = :id_category')
            ->andWhere('s.isActive = :true')
            ->setParameter('id_category', $id_category)
            ->setParameter('true',1)
            ->getQuery()
            ->getResult();
    }
}
