<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * ProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArticlesByProduct($id)
    {
        return $this->createQueryBuilder('a')
            ->innerJoin('a.products', 'p','WITH','p.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

    public function getArticleByProduct($id)
    {
        return $this->createQueryBuilder('a')
            ->innerJoin('a.products', 'p','WITH','p.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
