<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * ColorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductColorRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getColorByProducts($products)
//    {
//        $colors = $this->createQueryBuilder('c')
//            ->getQuery()
//            ->getResult();
//
//        return $colors;
//    }

    public function getColorsByCategory($id_category, $id_sub_category, $table = '', $criteria = '')
    {
        $qb = $this->createQueryBuilder('c')
            ->join('BDMNicolasBackendBundle:Product', 'p', 'WITH', 'c.id = p.color')
            ->join('BDMNicolasBackendBundle:ProductSubCategory', 's', 'WITH', 'p.sub_category = s.id');
        if ($table == 'alliance') {
            $qb->innerJoin('p.alliances', 'a', 'WITH', 'a.slug = :alliance')
                ->setParameter('alliance', $criteria);
        }
        if ($id_sub_category != 0) {
            $id_category = 0;
            $qb->andWhere('s.id = :id_sub_category')
                ->setParameter('id_sub_category', $id_sub_category);
        } else if ($id_category != 0) {
            $qb->join('BDMNicolasBackendBundle:ProductCategory', 'cat', 'WITH', 'cat.id = s.category')
                ->andWhere('cat.id = :id')
                ->setParameter('id', $id_category);
        }
        return $qb->getQuery()
            ->getResult();
    }

    public function getColorsByAlliance($alliance)
    {
        return $this->createQueryBuilder('c')
            ->join('BDMNicolasBackendBundle:Product', 'p', 'WITH', 'c.id = p.color')
            ->innerJoin('p.alliances', 'a', 'WITH', 'a.id = :id_alliance')
            ->setParameter('id_alliance', $alliance)
            ->getQuery()
            ->getResult();
    }

    public function getColorsByProducts($ids)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('c');
        $qb->from('BDMNicolasBackendBundle:ProductColor', 'c');
        $qb->where($qb->expr()->in('c.id', $ids));

        return $qb->getQuery()->getResult();
    }

}