<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * RegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getRegionsByCategory($id_category, $id_sub_category, $table = '', $criteria = '')
    {
        $qb = $this->createQueryBuilder('r')
            ->join('BDMNicolasBackendBundle:Product', 'p', 'WITH', 'r.id = p.region')
            ->join('BDMNicolasBackendBundle:ProductSubCategory', 's', 'WITH', 'p.sub_category = s.id');
        if ($table == 'alliance') {
            $qb->innerJoin('p.alliances', 'a', 'WITH', 'a.slug = :alliance')
                ->setParameter('alliance', $criteria);
        }
        if ($id_sub_category != 0) {
            $qb->where('s.id = :id_sub_category')
                ->setParameter('id_sub_category', $id_sub_category);
        } else {
            $qb->join('BDMNicolasBackendBundle:ProductCategory', 'c', 'WITH', 'c.id = s.category')
                ->where('c.id = :id')
                ->setParameter('id', $id_category);
        }
        try {
            return $qb->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return array();
        }
    }

    public function getRegionsByAlliance($alliance)
    {
        return $this->createQueryBuilder('r')
            ->join('BDMNicolasBackendBundle:Product', 'p', 'WITH', 'r.id = p.region')
            ->innerJoin('p.alliances', 'a', 'WITH', 'a.id = :id_alliance')
            ->setParameter('id_alliance', $alliance)
            ->getQuery()
            ->getResult();
    }

    public function getRegionsByProducts($ids)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('r');
        $qb->from('BDMNicolasBackendBundle:Region', 'r');
        $qb->where($qb->expr()->in('r.id', $ids));

        return $qb->getQuery()->getResult();
    }
}
