<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function loadUserByUsername($username)
    {
        return $this->createQueryBuilder('u')
            //->where('u.username = :username OR u.email = :email')
            ->where('u.username = :username')
            ->setParameter('username', $username)
            //->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function loadUserByEmail($email)
    {
        return $this->createQueryBuilder('u')
            //->where('u.username = :username OR u.email = :email')
            ->where('u.email = :email')
            ->setParameter('email', $email)
            //->setParameter('email', $username)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
