<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAll()
	{
		return $this->findBy(array(), array('date' => 'DESC'));
	}
}
