<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * ProductCategoryBannerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategoryBannerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBannersByCategory($id)
    {
        return $this->createQueryBuilder('b')
            ->where('b.category = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

}
