<?php

namespace BDM\Nicolas\BackendBundle\Repository;

/**
 * ProductImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductImageRepository extends \Doctrine\ORM\EntityRepository
{

    public function getImagesByProduct($id)
    {
        return $this->createQueryBuilder('i')
            ->where('i.product = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

    public function findImagesByProduct($id)
    {
        return $this->createQueryBuilder('i')
            ->where('i.product = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }

    public function getMainImageByProduct($id)
    {
        return $this->createQueryBuilder('i')
            ->where('i.product = :id')
            ->andWhere('i.isMain=1')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }

}
